### ISSUE TITLE
related to null safety?

### ISSUE THREAD

**Issue by nyck33** [PacktPublishing/Flutter-Cookbook#4]
For the pizza json chapter 8 I believe with a factory constructor, null cannot be returned.  Please update the code.  I have no idea what purpose the factory serves now except if there is a cache of instantiated pizzas in the pizza class which then could be used to optimize a bit by not having to instantiate every instance.  But I am unclear on the "how" this works under the hood.

**Comment by luketg8** [comment]
I believe that now due to null-safety this should be migrated to be a static method that returns null, which would then allow it to maintain it's intended functionality.

Please see this documentation - https://dart.dev/null-safety/faq#how-should-i-migrate-a-factory-that-can-return-null

**Comment by nithikpackt** [comment]
Thank you @luketg8 for the solution
